#!/usr/bin/env python3
"""
Generate embedded_font.{hpp,cpp} from the TTF files in src/common/fonts/.

The fonts are embedded as byte arrays for ImGui's AddFontFromMemoryTTF().
Each font gets its own pair (data pointer + size) under the
`caster::common::embedded_font` namespace:

    embedded_font::interRegular::data / size
    embedded_font::jetbrainsMono::data / size

The legacy `embedded_font::data` / `embedded_font::size` symbols are kept
as aliases of interRegular for backwards compatibility with any code that
still references them.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "src" / "common" / "fonts"

# (source filename, C++ symbol name, friendly description)
FONTS = [
    ("Inter-Regular.ttf",       "interRegular",   "Inter Regular (body font for all themes)"),
    ("JetBrainsMono-Regular.ttf", "jetbrainsMono", "JetBrains Mono Regular (mono font for keybinds / values)"),
]

OUT_HPP = ROOT / "src" / "common" / "embedded_font.hpp"
OUT_CPP = ROOT / "src" / "common" / "embedded_font.cpp"


def check_files_exist():
    missing = []
    for filename, _, _ in FONTS:
        path = FONTS_DIR / filename
        if not path.exists():
            missing.append(str(path))
    if missing:
        print("ERROR: missing font files:", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
        sys.exit(1)


def chunk_bytes(data: bytes, per_line: int = 12):
    """Yield strings of `per_line` comma-prefixed hex bytes."""
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        yield ",".join(f"0x{b:02x}" for b in chunk)


def gen_hpp() -> str:
    lines = [
        "// AUTO-GENERATED — DO NOT EDIT.",
        "// Source: src/common/fonts/*.ttf",
        "// Generated by: scripts/gen_embedded_font.py",
        "//",
        "// Exposes embedded TTF font data as byte arrays for ImGui's",
        "// AddFontFromMemoryTTF(). Each font has its own sub-namespace",
        "// with `data` (const uint8_t*) and `size` (size_t).",
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace caster::common::embedded_font {",
        "",
    ]
    for _, symbol, desc in FONTS:
        lines.append(f"// {desc}")
        lines.append(f"namespace {symbol} {{")
        lines.append(f"extern const std::uint8_t* const data;")
        lines.append(f"extern const std::size_t        size;")
        lines.append("}")
        lines.append("")
    # Legacy alias
    lines.append("// Legacy alias — points to Inter Regular (the original embedded font).")
    lines.append("// Prefer using the specific sub-namespaces above in new code.")
    lines.append("inline const std::uint8_t* const data = interRegular::data;")
    lines.append("inline const std::size_t        size = interRegular::size;")
    lines.append("")
    lines.append("} // namespace caster::common::embedded_font")
    lines.append("")
    return "\n".join(lines)


def gen_cpp() -> str:
    lines = [
        "// AUTO-GENERATED — DO NOT EDIT.",
        "// Source: src/common/fonts/*.ttf",
        "// Generated by: scripts/gen_embedded_font.py",
        "",
        "#include \"embedded_font.hpp\"",
        "",
        "namespace caster::common::embedded_font {",
        "",
    ]
    for filename, symbol, desc in FONTS:
        path = FONTS_DIR / filename
        data = path.read_bytes()
        lines.append(f"// {desc} — {len(data)} bytes of {filename}")
        lines.append(f"alignas(16) static const std::uint8_t k_{symbol}_data[{len(data)}] = {{")
        for chunk in chunk_bytes(data):
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")
        lines.append(f"const std::uint8_t* const {symbol}::data = k_{symbol}_data;")
        lines.append(f"const std::size_t        {symbol}::size = sizeof(k_{symbol}_data);")
        lines.append("")
    lines.append("} // namespace caster::common::embedded_font")
    lines.append("")
    return "\n".join(lines)


def main():
    check_files_exist()
    OUT_HPP.write_text(gen_hpp())
    print(f"Wrote {OUT_HPP}")
    OUT_CPP.write_text(gen_cpp())
    print(f"Wrote {OUT_CPP}")
    total_bytes = sum((FONTS_DIR / f).stat().st_size for f, _, _ in FONTS)
    print(f"Total embedded font data: {total_bytes} bytes ({total_bytes/1024:.1f} KB)")
    print("Done.")


if __name__ == "__main__":
    main()
