#!/usr/bin/env python3
"""
Generate embedded_font.{hpp,cpp} from src/common/font.ttf.

The font is exported as `extern const unsigned char caster_font_ttf[]` plus a
`caster_font_ttf_size` size_t, so C++ code can pass it directly to
ImGui::GetIO().Fonts->AddFontFromMemoryTTF().

We write each row as 12 hex bytes (e.g. 0x00,0x01,0x02,...) so the source
file stays readable and diffs are sane. Total source size for a 159 KB font
is ~600 KB of C++ — fine for a binary asset.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_TTF = ROOT / "src" / "common" / "font.ttf"
OUT_HPP = ROOT / "src" / "common" / "embedded_font.hpp"
OUT_CPP = ROOT / "src" / "common" / "embedded_font.cpp"

if not SRC_TTF.exists():
    print(f"ERROR: {SRC_TTF} not found", file=sys.stderr)
    sys.exit(1)

data = SRC_TTF.read_bytes()
print(f"Reading {SRC_TTF} ({len(data)} bytes)")

# --- Header ---------------------------------------------------------------
hpp = f"""// AUTO-GENERATED — DO NOT EDIT.
// Source: src/common/font.ttf
// Generated by: scripts/gen_embedded_font.py
//
// Exposes the embedded TTF font as a byte array for ImGui's
// AddFontFromMemoryTTF(). Use embedded_font::data / embedded_font::size.

#pragma once

#include <cstddef>
#include <cstdint>

namespace caster::common::embedded_font {{

// Pointer to the embedded TTF data. Valid for the lifetime of the program.
extern const std::uint8_t* const data;

// Number of bytes pointed to by `data`.
extern const std::size_t size;

}} // namespace caster::common::embedded_font
"""

OUT_HPP.write_text(hpp)
print(f"Wrote {OUT_HPP}")

# --- Source ---------------------------------------------------------------
# Chunk into 12 bytes per line for readability.
chunks = []
for i in range(0, len(data), 12):
    chunk = data[i:i+12]
    chunks.append(",".join(f"0x{b:02x}" for b in chunk))

cpp = f"""// AUTO-GENERATED — DO NOT EDIT.
// Source: src/common/font.ttf
// Generated by: scripts/gen_embedded_font.py

#include "embedded_font.hpp"

namespace caster::common::embedded_font {{

// {len(data)} bytes of font.ttf
alignas(16) static const std::uint8_t k_font_data[{len(data)}] = {{
""" + "\n".join("    " + c + "," for c in chunks) + f"""
}};

const std::uint8_t* const data = k_font_data;
const std::size_t        size = sizeof(k_font_data);

}} // namespace caster::common::embedded_font
"""

OUT_CPP.write_text(cpp)
print(f"Wrote {OUT_CPP} ({len(cpp)} chars, {len(chunks)} rows of 12 bytes)")
print("Done.")
