// src/common/controller/mapping.hpp
//
// Controller mapping model — ported from zzcaster's
// `src/dll/controller_mapper.zig`. Defines the types and persistence
// for the per-player controller mapping.
//
// Threading: NOT thread-safe. The launcher UI reads/writes mappings from
// the main thread only. The DLL side (when it reads the active mapping
// to generate inputs) must take a copy under a mutex if it polls from a
// different thread.

#pragma once

#include <cstdint>
#include <string>

namespace caster::common::controller {

// Type of input that a binding points to.
enum class InputType : std::uint8_t {
    None          = 0,  // empty binding
    SdlButton     = 1,  // SDL_JoystickGetButton(joy, index)
    SdlAxisPos    = 2,  // SDL_JoystickGetAxis(joy, index) > deadzone
    SdlAxisNeg    = 3,  // SDL_JoystickGetAxis(joy, index) < -deadzone
    SdlHat        = 4,  // SDL_JoystickGetHat(joy, hat_index) & direction_mask
    KeyboardKey   = 5,  // GetAsyncKeyState(index) & 0x8000
};

// Which game action a binding drives. Order matters — matches zzcaster
// exactly so the INI file stays byte-identical between Zig and C++.
enum class BindingTarget {
    None, A, B, C, D, E, AB, Start, FN1, FN2,
    Up, Down, Left, Right,
};

// Number of bindable actions (excludes None).
inline constexpr int kNumBindings = 13;

// A single input binding (which physical input fires which action).
struct InputBinding {
    InputType       type  = InputType::None;
    std::uint16_t   index = 0;

    // For SdlHat: index is packed as (direction << 8) | hat_index.
    // Direction codes (numpad layout, 5 = center, never bound):
    //   1=DL  2=D  3=DR
    //   4=L   5=?  6=R
    //   7=UL  8=U  9=UR
    static std::uint16_t pack_hat(std::uint8_t hat_index,
                                  std::uint8_t direction) {
        return static_cast<std::uint16_t>((direction << 8) | hat_index);
    }
    static std::uint8_t hat_index(std::uint16_t packed) {
        return static_cast<std::uint8_t>(packed & 0xFF);
    }
    static std::uint8_t hat_direction(std::uint16_t packed) {
        return static_cast<std::uint8_t>((packed >> 8) & 0xFF);
    }

    // Human-readable label for the UI ("Btn 2", "Ax 0+", "Hat0 U", "Key 0x20",
    // or "—" for None). Writes to `buf` (max 32 bytes) and returns a view
    // into it.
    std::string label() const;

    // INI serialization. Format examples:
    //   "none"
    //   "btn:2"
    //   "axp:4"
    //   "axn:1"
    //   "hat:0:8"   (hat_index:direction)
    //   "key:32"    (decimal VK code)
    std::string serialize() const;

    // Parse from INI string. Tolerant: returns None on any error.
    static InputBinding parse(const std::string& str);

    bool operator==(const InputBinding& o) const {
        return type == o.type && index == o.index;
    }
    bool operator!=(const InputBinding& o) const { return !(*this == o); }
};

// SOCD (Simultaneous Opposing Cardinal Directions) modes.
// Bitfield: bit 0 = neutralize L+R, bit 1 = neutralize U+D.
//   0 = invalid (treated as 1 by UI)
//   1 = L+R neutralize only
//   2 = U+D neutralize only
//   3 = both neutralize
enum class SocdMode : std::uint8_t {
    None           = 0,  // never generated by UI; treated as LrNeutralize
    LrNeutralize   = 1,
    UdNeutralize   = 2,
    BothNeutralize = 3,
};

// Full per-player controller mapping. 13 action bindings + analog stick
// config + SOCD + deadzone + device selection + macro toggle.
struct ControllerMapping {
    // Action bindings (default = Xbox 360/One layout).
    InputBinding a;       // default: sdl_button idx 2 (X)
    InputBinding b;       // default: sdl_button idx 3 (Y)
    InputBinding c;       // default: sdl_button idx 1 (B)
    InputBinding d;       // default: sdl_button idx 0 (A)
    InputBinding e;       // default: sdl_button idx 4 (LB)
    InputBinding ab;      // default: sdl_button idx 5 (RB) — A+B macro
    InputBinding start;   // default: sdl_button idx 7 (Start)
    InputBinding fn1;     // default: sdl_button idx 6 (Back/Select)
    InputBinding fn2;     // default: sdl_button idx 9 (R-stick press)
    InputBinding up;      // default: sdl_hat dir 8 hat 0
    InputBinding down;    // default: sdl_hat dir 2 hat 0
    InputBinding left;    // default: sdl_hat dir 4 hat 0
    InputBinding right;   // default: sdl_hat dir 6 hat 0

    // Analog stick config (for movement in addition to D-pad/hat).
    std::uint8_t  stick_x_axis = 0;  // SDL axis index for left-stick X
    std::uint8_t  stick_y_axis = 1;  // SDL axis index for left-stick Y

    // Deadzone in raw SDL axis units (range 0..32767). Default ~24%.
    std::uint32_t deadzone = 8000;

    // SOCD mode. Default = L+R neutralize.
    SocdMode      socd_mode = SocdMode::LrNeutralize;

    // Device selection. -1 = Keyboard, >=0 = SDL joystick index.
    int           device_index = 0;

    // Air dash macro toggle (9AB / 7AB). Off by default.
    bool          air_dash_macro = false;

    // Returns an Xbox 360/One default mapping (preserves current device_index).
    static ControllerMapping default_xbox();

    // Returns a mapping with all 13 action bindings cleared (set to None).
    // Preserves stick_x_axis, stick_y_axis, deadzone, socd_mode,
    // air_dash_macro, device_index.
    ControllerMapping cleared_bindings() const;

    // Access a binding by target. Returns nullptr for BindingTarget::None.
    InputBinding*       binding(BindingTarget t);
    const InputBinding* binding(BindingTarget t) const;
};

// Save both players' mappings to an INI file. Two sections, [Player1] and
// [Player2], each with 18 keys (device + 13 bindings + stick_x + stick_y
// + deadzone + socd + air_dash_macro). Returns true on success.
bool save_mapping(const std::string& path,
                  const ControllerMapping& p1,
                  const ControllerMapping& p2);

// Load both players' mappings from an INI file. Returns true on success;
// false if the file is missing or unreadable (in which case `p1` and `p2`
// are left as defaults). Tolerant of missing keys.
bool load_mapping(const std::string& path,
                  ControllerMapping& p1,
                  ControllerMapping& p2);

} // namespace caster::common::controller
