// AUTO-GENERATED — DO NOT EDIT.
// Source: src/common/font.ttf
// Generated by: scripts/gen_embedded_font.py
//
// Exposes the embedded TTF font as a byte array for ImGui's
// AddFontFromMemoryTTF(). Use embedded_font::data / embedded_font::size.

#pragma once

#include <cstddef>
#include <cstdint>

namespace caster::common::embedded_font {

// Pointer to the embedded TTF data. Valid for the lifetime of the program.
extern const std::uint8_t* const data;

// Number of bytes pointed to by `data`.
extern const std::size_t size;

} // namespace caster::common::embedded_font
