// AUTO-GENERATED — DO NOT EDIT.
// Source: src/common/fonts/*.ttf
// Generated by: scripts/gen_embedded_font.py
//
// Exposes embedded TTF font data as byte arrays for ImGui's
// AddFontFromMemoryTTF(). Each font has its own sub-namespace
// with `data` (const uint8_t*) and `size` (size_t).

#pragma once

#include <cstddef>
#include <cstdint>

namespace caster::common::embedded_font {

// Inter Regular (body font for all themes)
namespace interRegular {
extern const std::uint8_t* const data;
extern const std::size_t        size;
}

// JetBrains Mono Regular (mono font for keybinds / values)
namespace jetbrainsMono {
extern const std::uint8_t* const data;
extern const std::size_t        size;
}

// Legacy alias — points to Inter Regular (the original embedded font).
// Prefer using the specific sub-namespaces above in new code.
inline const std::uint8_t* const data = interRegular::data;
inline const std::size_t        size = interRegular::size;

} // namespace caster::common::embedded_font
